---

- name: version
  hosts: bigip
  connection: local
  gather_facts: false

  tasks:
    - name: setup provider
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ bigip_username }}"
          password: "{{ bigip_password }}"
          validate_certs: false
          server_port: 443

    - name: Wait for BIG-IP to be available
      bigip_wait:
        timeout: 300
        provider: "{{ provider }}"
      delegate_to: localhost
      register: status
      until: status is success
      retries: 10
      delay: 6

    - name: Collect BIG-IP information
      bigip_device_info:
        gather_subset: devices
        provider:
          user: "{{ bigip_user }}"
          password: "{{ bigip_password }}"
          server: "{{ inventory_hostname }}"
          validate_certs: no
      register: devices
      delegate_to: localhost

    - name: Create basic DNS resolver configuration for OCSP stapling
      bigip_dns_resolver:
        partition: "{{ bigip_partition }}"
        name: DNS-RESOLVER-OCSP
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost
      when: inventory_hostname == (devices.devices | selectattr('failover_state', 'search', 'active') | list | first).name

    - name: Add Let's Encrypt Staging X1 CA certificate
      bigip_ssl_certificate:
        partition: "{{ bigip_partition }}"
        name: Lets-Encrypt-Staging-X1
        content: |
          -----BEGIN CERTIFICATE-----
          MIIEqzCCApOgAwIBAgIRAIvhKg5ZRO08VGQx8JdhT+UwDQYJKoZIhvcNAQELBQAw
          GjEYMBYGA1UEAwwPRmFrZSBMRSBSb290IFgxMB4XDTE2MDUyMzIyMDc1OVoXDTM2
          MDUyMzIyMDc1OVowIjEgMB4GA1UEAwwXRmFrZSBMRSBJbnRlcm1lZGlhdGUgWDEw
          ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDtWKySDn7rWZc5ggjz3ZB0
          8jO4xti3uzINfD5sQ7Lj7hzetUT+wQob+iXSZkhnvx+IvdbXF5/yt8aWPpUKnPym
          oLxsYiI5gQBLxNDzIec0OIaflWqAr29m7J8+NNtApEN8nZFnf3bhehZW7AxmS1m0
          ZnSsdHw0Fw+bgixPg2MQ9k9oefFeqa+7Kqdlz5bbrUYV2volxhDFtnI4Mh8BiWCN
          xDH1Hizq+GKCcHsinDZWurCqder/afJBnQs+SBSL6MVApHt+d35zjBD92fO2Je56
          dhMfzCgOKXeJ340WhW3TjD1zqLZXeaCyUNRnfOmWZV8nEhtHOFbUCU7r/KkjMZO9
          AgMBAAGjgeMwgeAwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAw
          HQYDVR0OBBYEFMDMA0a5WCDMXHJw8+EuyyCm9Wg6MHoGCCsGAQUFBwEBBG4wbDA0
          BggrBgEFBQcwAYYoaHR0cDovL29jc3Auc3RnLXJvb3QteDEubGV0c2VuY3J5cHQu
          b3JnLzA0BggrBgEFBQcwAoYoaHR0cDovL2NlcnQuc3RnLXJvb3QteDEubGV0c2Vu
          Y3J5cHQub3JnLzAfBgNVHSMEGDAWgBTBJnSkikSg5vogKNhcI5pFiBh54DANBgkq
          hkiG9w0BAQsFAAOCAgEABYSu4Il+fI0MYU42OTmEj+1HqQ5DvyAeyCA6sGuZdwjF
          UGeVOv3NnLyfofuUOjEbY5irFCDtnv+0ckukUZN9lz4Q2YjWGUpW4TTu3ieTsaC9
          AFvCSgNHJyWSVtWvB5XDxsqawl1KzHzzwr132bF2rtGtazSqVqK9E07sGHMCf+zp
          DQVDVVGtqZPHwX3KqUtefE621b8RI6VCl4oD30Olf8pjuzG4JKBFRFclzLRjo/h7
          IkkfjZ8wDa7faOjVXx6n+eUQ29cIMCzr8/rNWHS9pYGGQKJiY2xmVC9h12H99Xyf
          zWE9vb5zKP3MVG6neX1hSdo7PEAb9fqRhHkqVsqUvJlIRmvXvVKTwNCP3eCjRCCI
          PTAvjV+4ni786iXwwFYNz8l3PmPLCyQXWGohnJ8iBm+5nk7O2ynaPVW0U2W+pt2w
          SVuvdDM5zGv2f9ltNWUiYZHJ1mmO97jSY/6YfdOUH66iRtQtDkHBRdkNBsMbD+Em
          2TgBldtHNSJBfB3pm9FblgOcJ0FSWcUDWJ7vO0+NTXlgrRofRT6pVywzxVo6dND0
          WzYlTWeUVsO40xJqhgUQRER9YLOLxJ0O6C8i0xFxAMKOtSdodMB3RIwt7RFQ0uyt
          n5Z5MqkYhlMI3J1tPRTp1nEt9fyGspBOO05gi148Qasp+3N+svqKomoQglNoAxU=
          -----END CERTIFICATE-----
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost
      when: inventory_hostname == (devices.devices | selectattr('failover_state', 'search', 'active') | list | first).name

    - name: Add Let's Encrypt X3 CA certificate
      bigip_ssl_certificate:
        partition: "{{ bigip_partition }}"
        name: Lets-Encrypt-X3
        content: |
          -----BEGIN CERTIFICATE-----
          MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
          MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
          DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
          SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
          GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
          AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
          q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
          SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
          Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
          a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
          /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
          AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
          CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
          bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
          c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
          VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
          ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
          MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
          Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
          AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
          uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
          wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
          X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
          PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
          KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
          -----END CERTIFICATE-----
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost
      when: inventory_hostname == (devices.devices | selectattr('failover_state', 'search', 'active') | list | first).name

    - name: Create OCSP stapling profile for Let's Encrypt Staging X1 CA
      bigip_ssl_ocsp:
        partition: "{{ bigip_partition }}"
        name: OCSP-STAPLE-Lets-Encrypt-Staging-X1
        cache_error_timeout: 300
        cache_timeout: "indefinite"
        clock_skew: 300
        dns_resolver: "/{{ bigip_partition }}/DNS-RESOLVER-OCSP"
        responder_url: "http://ocsp.stg-int-x1.letsencrypt.org"
        hash_algorithm: "sha1"
        status_age: 691200
        strict_responder_checking: "no"
        connection_timeout: 8
        connections_limit: 50
        trusted_responders: "Lets-Encrypt-Staging-X1.crt"
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost
      when: inventory_hostname == (devices.devices | selectattr('failover_state', 'search', 'active') | list | first).name

    - name: Create OCSP stapling profile for Let's Encrypt X3 CA
      bigip_ssl_ocsp:
        partition: "{{ bigip_partition }}"
        name: OCSP-STAPLE-Lets-Encrypt-X3
        cache_error_timeout: 300
        cache_timeout: "indefinite"
        clock_skew: 300
        dns_resolver: "/{{ bigip_partition }}/DNS-RESOLVER-OCSP"
        responder_url: "http://ocsp.int-x3.letsencrypt.org"
        hash_algorithm: "sha1"
        status_age: 691200
        strict_responder_checking: "no"
        connection_timeout: 8
        connections_limit: 50
        trusted_responders: "Lets-Encrypt-X3.crt"
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost
      when: inventory_hostname == (devices.devices | selectattr('failover_state', 'search', 'active') | list | first).name

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        save: yes
        provider: "{{ provider }}"
      delegate_to: localhost
      when: save_config == "1" and inventory_hostname == (devices.devices | selectattr('failover_state', 'search', 'active') | list | first).name

    - name: Sync configuration from device to group
      bigip_configsync_action:
        device_group: "{{ sync_device_group }}"
        sync_device_to_group: yes
        provider: "{{ provider }}"
      delegate_to: localhost
      when: sync_config == "1" and inventory_hostname == (devices.devices | selectattr('failover_state', 'search', 'active') | list | first).name

