---

- name: version
  hosts: bigip
  connection: local
  gather_facts: false

  tasks:
    - name: setup provider
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ bigip_username }}"
          password: "{{ bigip_password }}"
          validate_certs: false
          server_port: 443

    - name: Wait for BIG-IP to be available
      bigip_wait:
        timeout: 300
        provider: "{{ provider }}"
      delegate_to: localhost
      register: status
      until: status is success
      retries: 10
      delay: 6

    - name: Create/update key for cert
      bigip_ssl_key:
        partition: "{{ bigip_partition }}"
        name: "{{ cert_name }}.key"
        content: "{{ lookup('file', cert_key_file) }}"
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create/update certificate
      bigip_ssl_certificate:
        partition: "{{ bigip_partition }}"
        name: "{{ cert_name }}.crt"
        content: "{{ lookup('file', cert_file) }}"
        issuer_cert: "{{ cert_issuer }}"
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create/update certificate chain
      bigip_ssl_certificate:
        partition: "{{ bigip_partition }}"
        name: "{{ cert_name }}-CHAIN.crt"
        content: "{{ lookup('file', cert_chain_file) }}"
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create/update client SSL profile
      bigip_profile_client_ssl:
        partition: "{{ bigip_partition }}"
        name: "{{ clientssl_name }}"
        parent: "{{ clientssl_parent }}"
        cert_key_chain:
          - cert: "{{ cert_name }}.crt"
            key: "{{ cert_name }}.key"
            chain: "{{ cert_name }}-CHAIN.crt"
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost
      when: clientssl_manage == "1"

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        save: yes
        provider: "{{ provider }}"
      delegate_to: localhost
      when: save_config == "1"

    - name: Sync configuration from device to group
      bigip_configsync_action:
        device_group: "{{ sync_device_group }}"
        sync_device_to_group: yes
        provider: "{{ provider }}"
      delegate_to: localhost
      when: sync_config == "1"
